### ISSUE TITLE
Required ext-ruby-2.2.1 is not installed.

### ISSUE THREAD

**Issue by hopewise** [capistrano/bundler#118]
On the server, I have ruby 2.5.1, but when I try to deploy, I got this error:
```
 bundler:install
      01 ~/.rvm/bin/rvm default do bundle install --path /var/www/myapp_staging/shared/bundle --jobs 4 --without …
      01 Required ext-ruby-2.2.1 is not installed.
      01 To install do: 'rvm install "ext-ruby-2.2.1"'
      01 /usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bun…
      01        from /usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
      01        from /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/bundle:23:in `<main>'
      01        from /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:15:in `eval'
      01        from /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

Why it needs version ext-ruby-2.2.1 instead and how can I change that?

installed versions:
```
  * capistrano (3.13.0)
  * capistrano-bundler (1.6.0)
  * capistrano-local-precompile (1.2.0)
  * capistrano-npm (1.0.3)
  * capistrano-passenger (0.2.0)
  * capistrano-rails (1.4.0)
  * capistrano-rvm (0.1.2)
```

**Comment by hopewise** [comment]
Found that ruby version was specified in .ruby-verion file, I just changed it to use the installed version.
